<div id="delicious" class="linkbox">
  <h3>
    <a href="http://del.icio.us/pdc">del.icio.us/pdc</a>
  </h3>
  <p>Recent links:</p>
  <ul>
    <li>
      <a href="http://www.americanstate.org/vonnegut.html" title="Kurt Vonnegut &#xB6; George Orwell had five rules for better writing. Vonnegut has eight! EIGHT!">Eight rules for writing fiction</a>
    </li>
    <li>
      <a href="http://www.devthought.com/cssjavascript-true-power-fancy-menu/" title="A nice example of a fancy menu that uses JavaScript to add sparkle to a plain old HTML list in a fashion that does not require contorted HTML in your document.">CSS+Javascript power. Fancy menu</a>
    </li>
    <li>
      <a href="http://www.fontshop.com/index.cfm?fuseaction=verity.search&amp;searchstr=granby" title="FontShop &#xB6; A sanserif typeface designed in metal in the 1930s as a competitor to Gill Sans but actually closer to the original Johnston Underground font. Five weights, but no italics.">Granby</a>
    </li>
    <li>
      <a href="http://www.markboulton.co.uk/journal/comments/five_simple_steps_to_better_typography/" title="Mark Boulton &#xB6; Some fundamental typographical conventions translated in to HTML+CSS.">Five simple steps to better typography</a>
    </li>
    <li>
      <a href="http://webtypography.net/sxsw2007/" title="Slides and notes from SxSW 2007 &#xB6; Many of the conventions of traditional typography are forgotten or ignored by people creating web pages. This slide show from SXSW discusses some points of typography and how to achive them in HTML+CSS.">Web Typography Sucks</a>
    </li>
    <li>
      <a href="http://www.marksimonson.com/" title="Weblog of s type designer. &#x2018;I have frequently done lettering as part of design projects I'm working on. This has always been my favorite part, so in 2000 I opened my own shop specializing in lettering, typography and identity design.&#x2019;">Mark Simonson Studio / Notebook</a>
    </li>
    <li>
      <a href="http://www.fontbros.com/cgi-bin/commerce.cgi?preadd=action&amp;key=MASS-MEFA" title="Font Bros &#xB6; A faithful facsimile of an 8-point sans serif typeface as set on a 1940s-vintage hot metal typesetting machine.">Metallophile Sp 8 Family by Mark Simonson Studio</a>
    </li>
    <li>
      <a href="http://www.ms-studio.com/FontSales/proximanova.html" title="Mark Simonson's web site &#xB6; A sanserif font that I like the look of, combining geomertic and humanist influences, it looks clean and ultra-modern.">Proxima Nova</a>
    </li>
    <li>
      <a href="http://www.fontshop.com/index.cfm?fuseaction=catalog.fontpackage&amp;displayfontid=MSF.123353.0.0" title="Mark Simonson's clean and elegant sanserif is a geometric-humanist blend.">Proxima Nova Complete OT</a>
    </li>
    <li>
      <a href="https://bugzilla.mozilla.org/show_bug.cgi?id=70132" title="Mozilla Bug 70132 &#xB6; Discussion of whether and how to add embeddable fonts to Mozilla Firefox.">Support @font-face</a>
    </li>
    <li>
      <a href="http://www.webmonkey.com/webmonkey/98/01/index3a_page4.html?tw=design" title="Webmonkey &#xB6; Ancient scrolls describe how Bitstream and Netscape joined forces to make a system for embedding fonts in web pages to parallel Microsoft's TrueType-based WEFT system.">Embedded fonts in Netscape Navigator 4</a>
    </li>
    <li>
      <a href="http://www.microsoft.com/typography/web/embedding/weft3/default.htm" title="web font-embedding tool &#xB6; Microsoft's program for creating embedded fonts tailored to your web pages. (Windows only, and the embedded fonts work in MSIE only.)">Microsoft WEFT 3</a>
    </li>
    <li>
      <a href="http://msdn.microsoft.com/workshop/author/fontembed/font_embed.asp" title="In 1997, embedding special compressed, subsetted fonts in your web pages was all the rage. This is Microsoft's version of the idea, using the @font-face CSS rule and a program called WEFT.">Font Embedding in MSIE4</a>
    </li>
    <li>
      <a href="http://feedparser.org/" title="Mark Pilgrim&#x2019;s parse-at-all-costs reader for RSS and Atom feeds in Python. 3000 unit tests. Open source.">Universal Feed Parser</a>
    </li>
    <li>
      <a href="http://www.underware.nl/site2/index.php3?id1=underware&amp;id2=general&amp;id3=general" title="A graphic design studio which specializes in designing and producing typefaces (e.g., Fakir, a blackletter, and Auto, a sanserif with 3 italics). Based in Den Haag, Helsinki and Amsterdam.">Underware</a>
    </li>
    <li>
      <a href="http://www.isnotmagazine.org/" title="A magazine in the form of a 1.5m x 2m bill poster. It is the work of five young Melburnians, and from April 9, 2005, it has been on display at 50 outdoor poster sites in inner-city Melbourne.">Is Not Magazine</a>
    </li>
    <li>
      <a href="http://mezzoblue.com/" title="Dave Shea's weblog &#xB6; &quot;I&#x2019;m a Vancouver local and a freelance designer. I&#x2019;m happiest when designing, building, or creating something that didn&#x2019;t previously exist; this has taken many forms over the years.&quot;">mezzoblue</a>
    </li>
    <li>
      <a href="http://mezzoblue.com/archives/2007/02/21/icon_design/" title="mezzoblue &#xB6; Using vectors does not solve all your resizing problems: you need to tweak the small-scale versions to avoid fuzzy anti-aliasing. Similar issues to font-hinting at small sizes.">Icon Design: Sizing</a>
    </li>
    <li>
      <a href="http://www.macalope.com/" title="weblog &#xB6; Born of the earth, forged in fire, the Macalope was branded by the IT world &#x201C;non-standard&#x201D; and &#x201C;proprietary.&#x201D; A freak of nature. Part man, part Mac, part antelope, the Macalope set forth on a quest to save his beloved platform.">The Macalope</a>
    </li>
    <li>
      <a href="http://genshi.edgewall.org/" title="A Python library that provides components for parsing, generating and filtering HTML, XML and text content for output on the web. Includes a template language heavily inspired by Kid.">Genshi: Generate Content for the Web</a>
    </li>
    <li>
      <a href="http://www.matthewkroeker.com/splinter.htm" title="matthew.kroeker      industrial design &#xB6; Two chairs join neatly along a jagged line of displaed wooden slats to form a small bench.">splinter</a>
    </li>
    <li>
      <a href="http://www.roughlydrafted.com/RD/RDM.Tech.Q1.07/2A351C60-A4E5-4764-A083-FF8610E66A46.html" title="Pretty good summary of how Apple's DRM system works, and why the 'simple' changes outsiders have suggested (such as licensing to third parties, or selling non-DRM tunes alongside encumbered ones) would not be simple or even feasible.">How FairPlay Works: Apple's iTunes DRM Dilemma</a>
    </li>
    <li>
      <a href="http://vllg.com/Underware/Fakir/mudTyper+Weights/" title="village /// vllg.com &#xB6; A modern font based on broad-nibbed blackletter forms, but then reverse-engineered in to a normal-weight font with a curious, twisty, broken-line character.">Fakir</a>
    </li>
    <li>
      <a href="http://vllg.com/Thirstype/Kaas/mudTyper+Weights/" title="village /// vllg.com &#xB6; Amazingly chunky font based on traditional Germanic blackletter (Fraktur, Textura).">Kaas</a>
    </li>
    <li>
      <a href="http://vllg.com/Lux/LuxSans/mudTyper+Weights/" title="village /// vllg.com &#xB6; A sanserif font family with all the OpenType stuff and an amusing treatment of the top of the counter of D, P, B, and friends.">Lux Sans</a>
    </li>
    <li>
      <a href="http://www.ft.com/cms/s/11ba213e-bf7e-11db-9ac2-000b5df10621.html" title="FT.com / In depth &#xB6; A stark prediciton of future energy shortages. The transition to expensive and polluting reliance on 'unconventional oil' (like Canadian tar sands) could come sooner than most oil analysts had expected.">Study sees harmful hunt for extra oil</a>
    </li>
    <li>
      <a href="http://garrettdimon.com/" title="Blog of yet another web designer with an emphasis on simple, clean, and vivid typographical presnetation.">Garrett Dimon&#x2019;s weblog</a>
    </li>
    <li>
      <a href="http://bitworking.org/news/125/REST-and-WS" title="Joe Gregorio | BitWorking &#xB6; Outlines how WS-* and REST are appropriate at different levels of scalability, and how to go about designing a REST protocol.">REST and WS-*</a>
    </li>
    <li>
      <a href="http://bitworking.org/projects/atom/" title="Joe Gregorio &#xB6; Links to the latest draft of the APP, and to the IETF status page for the project.">Atom Publishing Protocol project page</a>
    </li>
    <li>
      <a href="http://www.macinhack.com/arch/feb/getting_the_most_out_of_your_laptop_battery.php" title="Tips for calibrating PowerBook and MacBook batteries, and monitoring their effectiveness.">Getting the msut out of your laptop battery</a>
    </li>
    <li>
      <a href="http://media.joyent.com/GridAccelerators-Whitepaper.pdf" title="application/pdf Object &#xB6; How Joyent's acellerators-by-the-yard system can make deploying your massive web application less of a hassle.">GridAccelerators-Whitepaper.pdf</a>
    </li>
  </ul>
</div>
